[package]
name = "pam-e4addkey"
version = "0.1.0"
authors = ["Raphael Catolino <raphael.catolino@gmail.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
pam_sm = { path = "../pam_sm_rust", version = "0.1" }
nix = "0.7.0"
ring = "0.6.1"
keyutils = { path = "../rust-keyutils", version = "0.2.1" }
